### ISSUE TITLE
App crash when alarming 

### ISSUE THREAD

**Issue by sushilsaini04** [lissy93/anti-theft-charge#2]
@Lissy93 @jaggs6  I have download this app but when i debug and test on my device it crashes on launching the alarm . but when i use apk uploaded on this it is working very well.  Pls tell me where is the problem.

**Comment by jaggs6** [comment]
Hard to tell without crssh logs

**Comment by sushilsaini04** [comment]
app crash net.as93.ScreenReciever not find andy reciever in this source code . Your Apk is working fine but when execute in source lot of code is missing.Please update source code 

Thanks
